accounts/urls.py
from django.urls import path

app_name = 'accounts'

urlpatterns = []

core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('about-me/', about, name='about'),
    path('contact-me/', contact, name='contact'),
    path('typography/', typography, name='typography'),
    path('blog/home/', blog, name='blog'),
    path('blog/single/', single, name='single'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.
class CommonInfo(models.Model):
    """
    This model is for the information that is going to be shared between the different models
    """
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)


class Contact(CommonInfo):
    """
    This model is for holding contact info
    """
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    message = models.TextField(null=True, blank=True)


    class Meta:
        ordering = ('updated', 'name',)
        verbose_name = 'People who Contacted'
        verbose_name_plural = 'People who Contacted'

core/forms.py
from django import forms

from .models import Contact

class ContactForm(forms.ModelForm):
    """
    This form is for handling the data for the Contact model explicitly
    """
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

accounts/views.py
from django.shortcuts import render

# Create your views here.
def test(request):
    return render(request, 'core/index.html')

core/views.py
from django.shortcuts import render, redirect

from .forms import ContactForm


def home(request):
    return render(request, 'core/home.html')

def about(request):
    return render(request, 'core/about.html')


def blog(request):
    return render(request, 'core/blog.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.ip_address = '127.0.0.1'
            contact.save()
            return redirect('core:home')
        
    else:
        form = ContactForm()
    context = {
        'form': form,
    }
    return render(request, 'core/contact.html', context)


def single(request):
    return render(request, 'core/single.html')


def typography(request):
    return render(request, 'core/typography.html')

templates/base.html
{% load static %}
<!doctype html>
<html class="home blog no-js" lang="en-US">

<head>
    <title>{% block title %}{% endblock title %} - by rightbros.co</title>

    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css" media="all" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Amatic+SC%3A400%2C700%7CLato%3A400%2C700%2C400italic%2C700italic&amp;ver=4.9.8"
        type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'css/print.css' %}" type="text/css" media="print" />
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
</head>

<body class="home sticky-menu sidebar-off" id="top">

    {% include 'includes/navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'includes/footer_widget.html' %}

    {% include 'includes/footer.html' %}
    {% include 'includes/search.html' %}

    <script>
        var ie9 = false;
    </script>
    <script src="{% static 'js/global-plugins.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/core/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="wrap full-wrap">
    <div class="main-wrap">

        <section class="main">
            <article class="post page">

                <div class="inner">
                    <h1>About me</h1>
                    <div class="post-content">
                        <p><img class="size-full alignleft rounded" src="/static/images/about-me.jpg" alt="about-clare"
                                width="300" height="300">
                            Hi, my name is Clare and I’m a serial blogger. I love life and more than anything in the
                            whole wide world, I love taking photographs.</p>
                        <p>Oh and did I mention, I quite like blogging?</p>
                        <p>I’m an aspring photographer and this is my little corner of the world, so take a look around
                            and let me know what you think… I’m on these little social networks too…</p>
                        <p>
                            <a target="_self" class="social twitter black" href="#"> Twitter </a>
                            <a target="_self" class="social facebook black" href="#"> Facebook&nbsp;</a>
                            <a target="_self" class="social instagram black" href="#">&nbsp;instagram&nbsp;</a>
                            <a target="_self" class="social flickr black" href="#"> flickr&nbsp;</a>
                        </p>

                    </div>
                </div>

            </article>
            <div class="border"></div>


        </section>


    </div><!-- /main-wrap -->


</div><!-- /wrap -->
{% endblock content %}

templates/core/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="wrap full-wrap">
    <div class="main-wrap">

        <section class="main">
            <article class="post page">

                <div class="inner">
                    <h1>Contact me</h1>
                    <div class="post-content">
                        <p>You can contact me using the following form :)</p>
                        <form id="fh5co_contact_form" method="POST">
                            {% csrf_token %}
                            <!-- <p>
                                <input type="text" name="name" value="" size="40" placeholder="Name*">
                            </p>
                            <p>
                                <input type="email" name="email" value="" size="40" placeholder="Email*">
                            </p>
                            <p>
                                <textarea name="message" cols="40" rows="10" placeholder="Your Message"></textarea>
                            </p> -->
                            {{ form.as_p }}
                            <p class="form-submit"><input type="submit" value="Send"></p>
                        </form>
                    </div>
                </div>

            </article>
            <div class="border"></div>

        </section>
    </div><!-- /main-wrap -->
</div><!-- /wrap -->
{% endblock content %}

templates/core/single.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="wrap full-wrap">
    <div class="main-wrap">
        <section class="main">


            <article class="post has-post-thumbnail">

  		        <span class="post-image">
                    <img width="916" height="611" src="/static/images/Lollipop.jpg" alt="">
  		        </span>


                <div class="inner">

                    <h1 class="entry-title">The Lollipop</h1>
                    <ul class="meta top">
                        <li class="time">
                            <time class="post-date updated" datetime="2015-02-02">February 2, 2015 </time>
                        </li>

                        <li class="comments">
                            <a href="single.html#respond">0 Comments</a>
                        </li>

                        <li class="author-m">
                            By <span class="vcard author"><span class="fn"><a href="blog.html" title="Posts by Clare Smith" rel="author">Clare Smith</a></span></span>
                        </li>

                    </ul>
                    <div class="post-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce at risus at lacus laoreet mollis sed id elit. Integer bibendum lobortis velit, eleifend commodo dui facilisis nec. Aliquam mi sapien, ultrices a ultrices non, sodales ut diam. Fusce semper risus eu magna placerat pulvinar. Nullam ac odio non ligula semper auctor. Fusce semper risus eu magna placerat pulvinar.</p>
                        <blockquote><p>“There are always two people in every picture: the photographer and the viewer.”<cite>Ansel Adams</cite></p></blockquote>
                        <p>Nullam ac odio non ligula semper auctor. Fusce semper risus eu magna placerat pulvinar. Nullam ac odio non ligula semper auctor. Aenean at dui dui, non scelerisque nisi. Morbi ullamcorper dapibus nisl, ullamcorper fringilla eros pulvinar et.</p>
                        <p>Nulla rhoncus elementum rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque a erat velit, venenatis porttitor mauris.</p>
                        <p>&nbsp;</p>
                        <p>Fusce semper risus eu magna placerat pulvinar. Nullam ac odio non ligula semper auctor. Fusce semper risus eu magna placerat pulvinar. Nullam ac odio non ligula semper auctor. Fusce semper risus eu magna placerat pulvinar. Nullam ac odio non ligula semper auctor. Aenean at dui dui, non scelerisque nisi. Morbi ullamcorper dapibus nisl, ullamcorper fringilla eros pulvinar et. Nulla rhoncus elementum rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque a erat velit, venenatis porttitor mauris.</p>
                    </div>


                    <ul class="meta bottom">
                        <li class="cat">Saved:  <a href="#">Blog</a>, <a href="#">Cute</a></li>
                    </ul>

                </div>
            </article>

            <nav class="pagination">
                <ul>
                    <li class="older-posts">
                        <span><a href="#" rel="prev"><i class="fa fa-chevron-left"></i> <span class="i">Prev</span></a></span>
                    </li>
                    <li class="share-link">
                        <a href="#share"><i class="fa fa-share-alt"></i><span class="i">Share</span></a>
                    </li>
                    <li class="newer-posts">
                        <span class="inactive"><span class="i">Next</span> <i class="fa fa-chevron-right"></i></span>
                    </li>

                </ul>
            </nav>





            <aside class="author-wrap">
                <span class="author-avatar"><img alt="" src="/static/images/about-me.jpg" class="avatar avatar-200 photo" height="200" width="200"></span>
                <div class="author-bio">
                    <h4><a href="blog.html">Clare Smith</a></h4>
                    <p>My name is Clare and I'm a serial blogger. I love life and more than anything in the whole wide world, I love taking photographs. Oh and did I mention, I quite like blogging?</p>
                    <div class="author-socials-wrap">

                        <a class="author-socials" href="http://twitter.com/fh5co" target="_blank"><i class="fa fa-twitter"></i><span>Twitter</span></a>
                        <a class="author-socials" href="http://facebook.com/fh5co" target="_blank"><i class="fa fa-facebook"></i><span>Facebook</span></a>
                        <a class="author-socials" href="#" target="_blank"><i class="fa fa-instagram"></i><span>Instagram</span></a>
                        <a class="author-socials" href="#" target="_blank"><i class="fa fa-pinterest"></i><span>Pinterest</span></a>
                        <a class="author-socials" href="#" target="_blank"><i class="fa fa-flickr"></i><span>Flickr</span></a>
                        <a class="author-socials" href="https://rightbros.co" target="_blank"><i class="fa fa-link"></i><span>Website</span></a>

                    </div>
                </div>

            </aside>




            <div class="related-posts">

                <h5>Related</h5>

                <div class="posts">

                    <aside class="related post has-post-thumbnail">

  		                <span class="post-image">
                            <a href="#" title="The Apothecary">
                                <img width="468" height="468" src="/static/images/Apothecary.jpg" alt=""></a>
                        </span>


                        <div class="inner">

                            <h6 class="entry-title">

                                <a href="#" title="The Apothecary">

                                    The Apothecary
                                </a>
                                <ul class="meta top">
                                    <li class="time">
                                        <time class="post-date updated" datetime="2015-01-31">January 31, 2015</time>
                                    </li>
                                </ul>

                            </h6>

                        </div>
                    </aside>


                    <aside class="related post has-post-thumbnail">

                        <span class="post-image">
                            <a href="#" title="The Flowers">
                                <img width="468" height="468" src="/static/images/Flowers.jpg" alt="" ></a>
                        </span>


                        <div class="inner">

                            <h6 class="entry-title">

                                <a href="#" title="The Flowers">The Flowers</a>
                                <ul class="meta top">
                                    <li class="time">
                                        <time class="post-date updated" datetime="2015-01-25">January 25, 2015</time>
                                    </li>
                                </ul>

                            </h6>

                        </div>
                    </aside>

                    <aside class="related post has-post-thumbnail">

                        <span class="post-image">
                            <a href="#" title="The Sunny Day">
                                <img width="468" height="468" src="/static/images/Sun.jpg" alt="">
                            </a>
                        </span>


                        <div class="inner">

                            <h6 class="post-title entry-title">

                                <a href="#" title="The Sunny Day">The Sunny Day</a>
                                <ul class="meta top">
                                    <li class="time">
                                        <time class="post-date updated" datetime="2015-01-21">January 21, 2015</time>
                                    </li>
                                </ul>

                            </h6>

                        </div>
                    </aside>


                </div></div>



            <div class="comments-wrapper">

                <div id="comments" class="inner">

                    <div class="comments-inner"><h3 id="respond-title">Comments (0)</h3></div>

                    <aside class="comments">
                    </aside>

                    <div id="respond" class="comment-respond">
                        <h3 id="reply-title" class="comment-reply-title">Leave a comment <small><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display:none;">Cancel reply</a></small></h3>
                        <form>
                            <p>Your email address will not be published. Required fields are marked <span class="required">*</span></p>
                            <p><label for="comment">Comment</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true" placeholder="Comment"></textarea></p><p class="comment-form-author"><label class="hidden" for="author">Name</label> <span class="required hidden">*</span><input id="author" name="author" type="text" value="" size="30" aria-required="true" placeholder="Name"></p>
                            <p><label for="email">Email</label> <span class="required ">*</span><input id="email" name="email" type="text" value="" size="30" aria-required="true" placeholder="Email"></p>
                            <p><label for="url">Website</label><input id="url" name="url" type="text" value="" size="30" placeholder="Website"></p>
                            <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Post Comment"></p>
                        </form>
                    </div><!-- #respond -->

                </div>

            </div>


        </section>


    </div><!-- /main-wrap -->


</div><!-- /wrap -->

{% endblock content %}

templates/includes/footer.html
<footer class="footer">
    <div class="footer-wrap">
        <div id="footer-text">&copy; 2018 Itsy.
            Designed by <a href="https://rightbros.co" target="_blank">rightbros</a>.</div>

        <a href="#top" id="btt">Top <i class="fa fa-chevron-up"></i></a>
    </div>
</footer>

templates/includes/footer_widget.html
{% load static %}
<div class="footer-widgets widget-count-4">

    <div class="wrap">

        <div class="mt-about-you-widget">
            <div class="widget footer">

                <img class="mt-about-avatar" src="/static/images/about-me.jpg" alt="Clare Itsy" />


                <h4>Clare Itsy</h4>

                <div class="mt-about-bio">
                    <p>Hi, my name is Clare and I&#039;m a serial blogger. I love life and more
                        than anything in the whole wide world, I love taking photographs. Oh and did I mention, I
                        quite like
                        blogging?</p>
                </div>


            </div>
        </div>
        <div class="widget footer">
            <h4>Recent Posts</h4>
            <ul>
                <li>
                    <a href="#">The Lollipop</a>
                </li>
                <li>
                    <a href="#">Running through Chicago</a>
                </li>
                <li>
                    <a href="#">The Apothecary</a>
                </li>
                <li>
                    <a href="#">The Flowers</a>
                </li>
                <li>
                    <a href="#">The Sunny Day</a>
                </li>
            </ul>
        </div>
        <div class="widget footer">
            <h4>Categories</h4>
            <ul>
                <li class="cat-item cat-item-6">
                    <a href="#" title="A cute little description would go in here">Blog</a>
                </li>
                <li class="cat-item cat-item-7">
                    <a href="#" title="A cute little description would go in here">Cute</a>
                </li>
                <li class="cat-item cat-item-8">
                    <a href="#">Fitness</a>
                </li>
                <li class="cat-item cat-item-9">
                    <a href="#">Fun</a>
                </li>
            </ul>
        </div>
        <div class="widget footer">
            <h4>Gallery</h4>
            <div class="textwidget">
                <img src="/static/images/gallery.png" alt="">
            </div>
        </div>
    </div>

</div>

templates/includes/navbar.html
{% load static %}
<header class="header">

    <div class="header-wrap">

        <div class="logo plain logo-left">
            <div class="site-title">
                <a href="{% url 'core:home' %}" title="Go to Home">The SKY</a>
            </div>
        </div><!-- /logo -->


        <nav id="nav" role="navigation">
            <div class="table">
                <div class="table-cell">
                    <ul id="menu-menu-1">
                        <li class="menu-item">
                            <a href="{% url 'core:home' %}">Home</a></li>
                        <li class="menu-item">
                            <a href="{% url 'core:about' %}">About me</a></li>
                        <li class="menu-item">
                            <a href="#">Dropdown</a>
                            <ul class="sub-menu">
                                <li class="menu-item">
                                    <a href="#">Cute</a></li>
                                <li class="menu-item">
                                    <a href="#">Fun</a></li>
                                <li class="menu-item">
                                    <a href="#">Fitness</a>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item">
                            <a href="{% url 'core:blog' %}">Blog</a>
                            <ul class="sub-menu">
                                <li class="menu-item">
                                    <a href="{% url 'core:single' %}">Single</a></li>
                            </ul>
                        </li>
                        <li class="menu-item">
                            <a href="{% url 'core:typography' %}">Typography</a></li>
                        <li class="menu-item">
                            <a href="{% url 'core:contact' %}">Contact me</a></li>
                        <li class="menu-inline menu-item">
                            <a title="Twitter" href="http://twitter.com/Rightbros1">
                                <i class="fa fa-twitter"></i><span class="i">Twitter</span>
                            </a></li>
                        <li class="menu-inline menu-item">
                            <a title="Facebook" href="http://www.facebook.com/Rightbros">
                                <i class="fa fa-facebook"></i><span class="i">Facebook</span>
                            </a></li>
                        <li class="menu-inline menu-item">
                            <a title="Flickr" href="#"><i class="fa fa-flickr"></i><span class="i">Flickr</span></a>
                        </li>
                        <li class="menu-inline menu-item">
                            <a title="Instagram" href="https://instagram.com/the.monu.tyagi/">
                                <i class="fa fa-instagram"></i><span class="i">Instagram</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <a href="#nav" class="menu-trigger"><i class="fa fa-bars"></i></a>

        <a href="#topsearch" class="search-trigger"><i class="fa fa-search"></i></a>

    </div>

</header>

templates/includes/search.html
{% load static %}
<div id="topsearch">
    <div class="table">
        <div class="table-cell">
            <form role="search" method="get" class="searchform" action="index.html">
                <div>
                    <input type="text" value="" name="s" class="s" placeholder="Type and hit enter" />
                    <input type="submit" class="searchsubmit" value="Search" />
                </div>
            </form>
        </div>
    </div>
    <a href="#topsearch" class="search-trigger"><i class="fa fa-times"></i></a>
</div>